---
- name: Create CA if not exists
  shell: >
    docker service create \
      --mode global \
      --name cadvisor \
      --constraint 'node.role==manager' \
      --publish 8090:8080 \
      --log-opt max-size={{ ca_log_max_size }} \
  register: ca_service_create_output