---
- name: Check if CA exists as a service on Swarm
  shell: docker network ls --quiet --filter "name={{ ca_network_name }}"
  register: ca_network_output

- name: Create CA network if not exists
  shell: >
    docker network create --driver overlay --attachable --subnet 10.3.0.0/24 {{ ca_network_name }}
  when: (ca_network_output.stdout | trim == '')

