version: '2.0'

services:
  terraform:
    image: hashicorp/terraform:0.9.4
    working_dir: /workdir
    environment:
      # amazon
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - .:/workdir

