route:
    repeat_interval: 30m
    group_interval: 30m
    receiver: 'rocketchat'

receivers:
    - name: 'rocketchat'
      webhook_configs:
          - send_resolved: false
            url: 'http://localhost:3080/hooks/vTh6i2DZBhAd9xi3F/6sryY9doW7kpWTXbGEciuWazzcPJcZ54QYsEkre2u7QjqcJK'
