---
- include: setup_docker.yml
  tags:
    - setup_docker

- include: setup_swarm.yml
  tags:
    - setup_swarm

- include: deploy_stack.yml
  tags:
    - deploy_stack
  when: not deploy is undefined

