route:
    repeat_interval: 30m
    group_interval: 30m
    receiver: 'rocketchat'

receivers:
    - name: 'rocketchat'
      webhook_configs:
          - send_resolved: false
            #url: 'http://34.228.141.15:3080/hooks/vTh6i2DZBhAd9xi3F/6sryY9doW7kpWTXbGEciuWazzcPJcZ54QYsEkre2u7QjqcJK'
            url: 'http://34.228.141.15:3080/hooks/9SSH7mMMmt5xPgfdf/W8mokhzemPzbugivn5mLP8jBZcRF942Qkw4tYyxsDpWzP2vv'
